apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: oih-dev-ns
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influx-db
        image: influxdb:latest
        ports:
        - containerPort: 8086
        env:
        - name: INFLUXDB_LOGGING_LEVEL
          value: "error"
        - name: INFLUXDB_REPORTING_DISABLED
          value: "true"
        - name: INFLUXDB_DATA_QUERY_LOG_ENABLED
          value: "false"
        - name: INFLUXDB_DATA_TRACE_LOGGING_ENABLED
          value: "false"
        - name: INFLUXDB_HTTP_LOG_ENABLED
          value: "false"
        - name: INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED
          value: "false"
        - name: INFLUXDB_DATA_ENGINE
          value: "tsm1"
        volumeMounts:
        - name: influx-pdisk
          mountPath: /var/lib/influxdb
        livenessProbe:
          httpGet:
            port: 8086
            path: /ping
          initialDelaySeconds: 120
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            port: 8086
            path: /ping
          initialDelaySeconds: 10
          timeoutSeconds: 1
      volumes:
      - name: influx-pdisk
        persistentVolumeClaim:
          claimName: influx-pvc
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: oih-dev-ns
  labels:
    app: influxdb
spec:
  type: NodePort
  selector:
    app: influxdb
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086
