apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-analytics
  namespace: oih-dev-ns
  labels:
    app: reports-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports-analytics
  template:
    metadata:
      labels:
        app: reports-analytics
    spec:
      containers:
      - name: reports-analytics
        image: openintegrationhub/reports-analytics:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: reports-analytics
        env:
        - name: GRAFANA_TOKEN
          valueFrom:
            secretKeyRef:
              name: reports-analytics
              key: grafanatoken
        - name: IAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: reports-analytics
              key: iamtoken
        - name: MONGODB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: reports-analytics
              key: mongourl
        livenessProbe:
          httpGet:
            port: 3000
            path: /healthcheck
          initialDelaySeconds: 120
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            port: 3000
            path: /healthcheck
          initialDelaySeconds: 10
          timeoutSeconds: 1
  minReadySeconds: 10
  revisionHistoryLimit: 2
